### ISSUE TITLE
好奇运行这个成本如何？

### ISSUE THREAD

**Issue by wong2** [guaguaguaxia/weekly_report#11]
这几天流量应该挺大的，成本都是作者自己承担了吧，大概有多少呢？

**Comment by guaguaguaxia** [comment]
wong老师你好，推特关注你很久了，现在有点忙，等我空闲时我发邮件联系你

**Comment by showunclex** [comment]
可以看下成本有多大吗？目前看起来扩展空间应该还是有的

**Comment by guaguaguaxia** [comment]
看了我代码的都能看出来我是用多个key来应对并发的。一个key有免费的18美元，上线的这几天平均一天50个key。用购买账号的方式一天的成本是150，如果是正规来用API，那就是900美元

**Comment by anc95** [comment]
@guaguaguaxia 可以众筹 API key
