### ISSUE TITLE
点击生成没反应

### ISSUE THREAD

**Issue by Akilio1** [guaguaguaxia/weekly_report#19]
点击生成报告之后无法生成，后台console打印了key和111222之后就没有输出了

**Comment by Akilio1** [comment]
### 
![image](https://user-images.githubusercontent.com/108854218/218759399-c1283609-2c6c-4808-872a-6adeb046c562.png)

**Comment by guaguaguaxia** [comment]
你的key是有效的吗

**Comment by Akilio1** [comment]
发现是Key用完了，目前成功了
