### ISSUE TITLE
使用 Vercel部署点击生成按钮没有反应

### ISSUE THREAD

**Issue by axingde** [guaguaguaxia/weekly_report#24]
大佬，使用用vercel部署，页面可以访问，输入内容点击生成没有反应，类似于您网站当前web点击效果，可能是什么情况导致，openAI的APIkey在环境变量有配置和另外两个环境变量
![image](https://user-images.githubusercontent.com/65204372/219268111-07157feb-8900-4014-bd8f-9469e85a5e4e.png)
![image](https://user-images.githubusercontent.com/65204372/219268817-e5f06ee4-b4ff-446a-94e9-bde36c84ecee.png)

**Comment by guaguaguaxia** [comment]
你看一下我下线前的那次commit，把loading效果和onclick函数去掉了，你找到那次commit改回去就行了

**Comment by kensam0805** [comment]
是否能提供下未下线的整体文件。因为有点看不懂

**Comment by axingde** [comment]
![image](https://user-images.githubusercontent.com/65204372/219294558-b31df2a6-97c3-4e19-9b84-f2671babea55.png)
我修改回78c4c4ac8b25b03cf943c119535955e419efcc7c commit的内容，现在效果是点击一直处于加载中

**Comment by axingde** [comment]
![image](https://user-images.githubusercontent.com/65204372/219295046-870681e3-e664-43f4-aa9b-30f84ab92bc9.png)

**Comment by kensam0805** [comment]
还是等作者更新一键操作

**Comment by guaguaguaxia** [comment]
https://github.com/guaguaguaxia/weekly_report/commit/e0ec0f20aa43061802968888b2613206d85d6a80

**Comment by guaguaguaxia** [comment]
> ![image](https://user-images.githubusercontent.com/65204372/219295046-870681e3-e664-43f4-aa9b-30f84ab92bc9.png)

你的key是你自己的吗

**Comment by axingde** [comment]
key是我自己的


> > ![image](https://user-images.githubusercontent.com/65204372/219295046-870681e3-e664-43f4-aa9b-30f84ab92bc9.png)
> 
> 你的key是你自己的吗

是的，key是我自己的

**Comment by guaguaguaxia** [comment]
把你网站发出来可以吗

**Comment by kensam0805** [comment]
https://weekly-report-q4bp.vercel.app/zh

**Comment by axingde** [comment]
> 把你网站发出来可以吗

https://weekly-report-g6lkdaukd-axingde.vercel.app/zh

**Comment by axingde** [comment]
![image](https://user-images.githubusercontent.com/65204372/219299358-5dedec8b-6692-48b5-9bba-6479b78527c1.png)


> key是我自己的
> 
> > > ![image](https://user-images.githubusercontent.com/65204372/219295046-870681e3-e664-43f4-aa9b-30f84ab92bc9.png)
> > 
> > 
> > 你的key是你自己的吗
> 
> 是的，key是我自己的

**Comment by guaguaguaxia** [comment]
换完key后要重启

**Comment by kensam0805** [comment]
作者 方便修改下能执行的源码   这样方便小白操作？  谢谢

**Comment by guaguaguaxia** [comment]
> 作者 方便修改下能执行的源码 这样方便小白操作？ 谢谢

下班后看看

**Comment by axingde** [comment]
> 换完key后要重启

![image](https://user-images.githubusercontent.com/65204372/219311313-cf84c3c3-6191-47d6-8c73-e323a109ba9d.png)
github修改后vercel不是会自动拉取更新吗，还需要在哪重启吗

**Comment by guaguaguaxia** [comment]
@kensam0805  代码恢复了
