### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by pluto-ctrl** [guaguaguaxia/weekly_report#26]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/69779230/219315796-c4526f24-f713-4c45-bffa-fb4f39310664.png">
大佬，你有出现过这个错误吗

**Comment by pluto-ctrl** [comment]
点击生成报告后就报错了

**Comment by furunhao** [comment]
如果你填写了自己的 API_Key ，那么把本地文件.env.example要改成.env 。我是这样操作的，就可以生成周报了
