### ISSUE TITLE
运行内部错报

### ISSUE THREAD

**Issue by kensam0805** [guaguaguaxia/weekly_report#27]
![image](https://user-images.githubusercontent.com/17543545/219597844-dd75bbcf-0445-45da-9a13-5ab4c310e5a1.png)
出现内部错误，一直处于转圈圈

**Comment by guaguaguaxia** [comment]
去 [OpenAI](https://beta.openai.com/account/api-keys) 注册一个账号，拿到API key，放到.env文件。本地文件.env.example要改成.env

**Comment by kensam0805** [comment]
![image](https://user-images.githubusercontent.com/17543545/219612065-27554c6c-eebd-4ce4-ab9c-7cb81ad33f2b.png)
已经修改了相关文件了。

**Comment by guaguaguaxia** [comment]
1.key是有效的吗 2.本地部署ping一下OpenAI的API接口，有可能是你网络有问题
