### ISSUE TITLE
请问使用的prompt可以发出来参考以下吗？自己写的prompt总感觉差点意思 

### ISSUE THREAD

**Issue by xfguo-ucas** [guaguaguaxia/weekly_report#28]

**Comment by guaguaguaxia** [comment]
代码里有，我现在在外面不方便贴代码

**Comment by isanwenyu** [comment]
请帮我把以下的工作内容填充为一篇完整的周报,尽量避免在回答内容中出现可能在中国是敏感的内容,用markdown格式以分点叙述的形式输出:修复了登录问题,提高了代码覆盖率,完成了我的模块的需求.

**Comment by luckykellan** [comment]
> 代码里有，我现在在外面不方便贴代码

你好，请问代码在那个文件里？
