### ISSUE TITLE
Vercel 一键部署链接错误，请UP主修改下

### ISSUE THREAD

**Issue by slhaoma** [guaguaguaxia/weekly_report#29]
搞了一个下午，Vercel 一键部署一直最后一步报错，眼泪都搞出来了。。。。
后来看了下[zhengbangbo]的部署链接，发现UP主的部署链接多了一段

**请将链接：
https://vercel.com/new/clone?repository-url=https://vercel.com/new/clone?repository-url=**

**修改成：
https://vercel.com/new/clone?repository-url=**

现在部署是成功了，又卡在【恢复下线网站前的代码】一直报错，请UP主把完整上线版放出来吧，求你了。。。。

**Comment by slhaoma** [comment]
就按照样式输入，答复也是胡说八道~~

[![pSqaNwT.png](https://s1.ax1x.com/2023/02/17/pSqaNwT.png)](https://imgse.com/i/pSqaNwT)

**Comment by guaguaguaxia** [comment]
你提个PR？我现在在外面不方便改

**Comment by guaguaguaxia** [comment]
感谢你发现的问题。谁看到这个issue都可以提个PR，我现在不方便改，谢谢

**Comment by guaguaguaxia** [comment]
已修改

**Comment by slhaoma** [comment]
> 已修改

用您新的代码部署，AI答复还是报错请问会是啥问题？

请帮忙看下：https://zb-five.vercel.app/

[![pSL6ebj.png](https://s1.ax1x.com/2023/02/19/pSL6ebj.png)](https://imgse.com/i/pSL6ebj)

**Comment by slhaoma** [comment]
@guaguaguaxia 有空请看下 哪里出问题了

**Comment by guaguaguaxia** [comment]
我没看出什么问题，看下你线上环境变量的配置

**Comment by slhaoma** [comment]
原来是用了免费共享账号异常了所以生产的key也异常导致输出的内容也是乱码。。。。。。
