### ISSUE TITLE
一直Loading求帮助

### ISSUE THREAD

**Issue by shenyaocan** [guaguaguaxia/weekly_report#31]
D:\ChatGPT\weekly_report-main>npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\ChatGPT\weekly_report-main\.env
event - compiled client and server successfully in 2.6s (215 modules)
wait  - compiling...
event - compiled successfully in 213 ms (178 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 113 ms (216 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 987 ms (642 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
Streamed response:
Streamed response:
Streamed response:
wait  - compiling /api/generate (client and server)...
event - compiled successfully in 131 ms (43 modules)
sk-DN96xk5ue7cNat18gNXTT3BlbkFJiytxy6ylDy7RXXJG
111222
sk-DN96xk5ue7cNat18gNXTT3BlbkFJiytxy6ylDy7RXXJG
111222

**Comment by shenyaocan** [comment]
![image](https://user-images.githubusercontent.com/39956271/219687159-ab0b3941-5d3c-4f5f-bba1-874bbf919ed8.png)

**Comment by anc95** [comment]
@shenyaocan 直接贴你的 OPEN_API_KEY 在这不太好吧

**Comment by guaguaguaxia** [comment]
看下README和历史issue，有没有能帮到你的
