### ISSUE TITLE
感谢作者大佬，借鉴学习了下，现在已经上线了

### ISSUE THREAD

**Issue by wuliqq** [guaguaguaxia/weekly_report#35]
点击下面这个链接可以体验下：
[周报生成器](https://aicodehelper.com/tools/index.html#/)

**Comment by Sunknight945** [comment]
![image](https://user-images.githubusercontent.com/52992100/219948166-24912442-24e8-4f20-81d6-15ce56d41f90.png)
 这个接口, 有频率限制嘛?

**Comment by wuliqq** [comment]
> ![image](https://user-images.githubusercontent.com/52992100/219948166-24912442-24e8-4f20-81d6-15ce56d41f90.png) 这个接口, 有频率限制嘛?

一般都是调用的openai的，是有限制的
