### ISSUE TITLE
Vercel 部署完成打不开

### ISSUE THREAD

**Issue by WhuRan** [guaguaguaxia/weekly_report#37]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/33825650/220011665-3124c913-b705-47aa-b706-8ba420f9a049.png">
使用Vercel 一键部署之后，显示状态“Ready”了，但是点击Visit按钮链接打不开，请问这是什么原因呢，需要绑定自己的网址吗

**Comment by guaguaguaxia** [comment]
可能是Vercel的DNS还没起效，你试下翻墙工具开全局访问试试
