### ISSUE TITLE
本地编译部署

### ISSUE THREAD

**Issue by X-777** [guaguaguaxia/weekly_report#38]
请问一下，本地编译部署是怎么弄的，npm run build进行编译么？编译后的文件是在哪儿？

**Comment by guaguaguaxia** [comment]
你问的问题README都有

**Comment by X-777** [comment]
![image](https://user-images.githubusercontent.com/3581889/220278749-63aa3061-2b05-4502-8476-5ebc00e60f7e.png)
这里只有本地运行，还有线上部署，没有提到本地的打包部署额

**Comment by guaguaguaxia** [comment]
本地执行这两条命令就可以跑起来了

**Comment by X-777** [comment]
我是想打包编译后部署到自己的云服务器上

**Comment by guaguaguaxia** [comment]
我不是很熟悉项目所设计的技术栈要怎么手动部署。我项目里的线上一键部署功能不需要额外的服务器，你可以试试，或许也是你想要的

**Comment by X-777** [comment]
vercel被墙了，所以才想部署自己的服务器上，那我再看看
