### ISSUE TITLE
这个不能有cf 部署吗

### ISSUE THREAD

**Issue by aiastia** [guaguaguaxia/weekly_report#4]
RT 失败

**Comment by guaguaguaxia** [comment]
你好，我是后端，不是很清楚你说的cf是什么。如果你想自己部署请看README

**Comment by zhengbangbo** [comment]
这个项目用到了 Vercel 的 Edge Function。如果要用 Cloudflare 部署需要修改成 cf Edge Function 的配置。

**Comment by aiastia** [comment]
> 这个项目用到了 Vercel 的 Edge Function。如果要用 Cloudflare 部署需要修改成 cf Edge Function 的配置。

具体如何修改 我目前配置了部署失败了

**Comment by zhengbangbo** [comment]
> > 这个项目用到了 Vercel 的 Edge Function。如果要用 Cloudflare 部署需要修改成 cf Edge Function 的配置。
> 
> 具体如何修改 我目前配置了部署失败了

这个恐怕需要你自己研究了。我也才刚接触两周，只知道各家都有这种服务完成第三方调用。
