### ISSUE TITLE
开源了个寂寞，报错，apikey都填写了

### ISSUE THREAD

**Issue by codesdevs** [guaguaguaxia/weekly_report#45]
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/58060741/222087185-9cf0b14d-52b5-4712-ba99-44d986c6e9bf.png">
<img width="737" alt="image" src="https://user-images.githubusercontent.com/58060741/222087241-81ed5431-cf5b-4fb1-b542-b9ceec09332b.png">

**Comment by guaguaguaxia** [comment]
我暂时不是很擅长前端技术栈，最近正在学习，你可以参考错误给出的链接：[https://nextjs.org/docs/messages/class-component-in-server-component，](https://nextjs.org/docs/messages/class-component-in-server-component%EF%BC%8C) 看他的提示貌似这是一个很常见的错误。我本地用最新代码复现不出来

**Comment by LionZzzi** [comment]
我报的也是这个错误
