### ISSUE TITLE
部署到vercel后还是报错

### ISSUE THREAD

**Issue by dadaewqq** [guaguaguaxia/weekly_report#46]
大佬，因为某些原因，国内部署的api现在没法正常用，所以想着部署到vercel上，api也填好了，生成周报时，/api/generate报错500，着啥情况？

**Comment by guaguaguaxia** [comment]
你的key是有效的吗

**Comment by guaguaguaxia** [comment]
好的好的，今晚或者周末看看，方便发一下你的网站吗

**Comment by guaguaguaxia** [comment]
![image](https://user-images.githubusercontent.com/18466048/222634084-6adf46b6-a503-4323-bdf6-d2670d30de81.png)
你的这个文件不知道为什么没生成，麻烦你看下Vercel的部署日志，看下能不能提供更多信息

**Comment by sishuiwuxie** [comment]
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/30409095/222649833-eef70d3e-c1b3-4edf-9a3d-1bd09ff8500b.png">

**Comment by hbyxzpf** [comment]
[deploy](https://vercel.com/new/clone?repository-url=https://github.com/guaguaguaxia/weekly_report&env=OPENAI_API_KEY,NEXT_PUBLIC_USE_USER_KEY,OPENAI_MODEL&project-name=weekly_report&repo-name=weekly_report) 用新的deploy链接, 丢失了OPENAI_MODEL 全局变量

**Comment by guaguaguaxia** [comment]
@hbyxzpf  昨天OpenAI发布了新模型 gpt-3.5-turbo，现在项目默认用这个模型了，如果你想换模型，可以根据我这个commit替换回去。https://github.com/guaguaguaxia/weekly_report/commit/505cb0fafe25e813d7199f17170dfe6b70d18c82

**Comment by hbyxzpf** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/20298039/222669026-0f6a163c-4fc3-4da7-a5f2-d817e303981c.png">
@guaguaguaxia 你的代码目前是写死的.然后没有替换env.openai_model

**Comment by hbyxzpf** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/20298039/222669026-0f6a163c-4fc3-4da7-a5f2-d817e303981c.png">
@guaguaguaxia 你的代码目前是写死的.然后没有替换env.openai_model

**Comment by guaguaguaxia** [comment]
@hbyxzpf  啊！我马上改，忘了这段要删掉了

**Comment by guaguaguaxia** [comment]
@dadaewqq  改好了，你再重新一键部署看看，或者看下我刚刚提交的代码，删掉这段：https://github.com/guaguaguaxia/weekly_report/commit/3c2bb7bfc0129264e5b39d53956d5b0dd548d0f8
