### ISSUE TITLE
.env Api暴露问题

### ISSUE THREAD

**Issue by lizhangsheng0876** [guaguaguaxia/weekly_report#6]
根据文档部署到了vercel 但是点击生成周报，并没有访问，但在本地可以正常使用，应该是api暴露了，导致key失效，请问如何解决

**Comment by guaguaguaxia** [comment]
你好，感谢你提的issue。你提的问题我并没有很好地理解，希望你对以下几点再做阐述。
- 「并没有访问」，是访问哪里？
- 「API暴露」，没有get到
- 「key失效」是什么意思，key是要自己去OpenAI后台申请的

**Comment by lizhangsheng0876** [comment]
不好意思 本人比较菜，已经解决了

**Comment by karasHou** [comment]
我在自己利用申请的api开发页面的时候也遇到了你一样的问题（api key提示失效），应该是api不知道什么时候暴露了（可能chat有检测机制？），想问问你是怎么解决的，可以给我提供一个思路吗？ @lizhangsheng0876
