### ISSUE TITLE
请问如何部署哈哈哈，后端程序员对这个不熟

### ISSUE THREAD

**Issue by XiaoSiHwang** [guaguaguaxia/weekly_report#7]

**Comment by guaguaguaxia** [comment]
看README

**Comment by joyol** [comment]
一样后端，不熟看得头大
1.去platform.openai.com网站注册个账号，拿到apikey
2.把key填到项目.env.example文件中
3.安装python，用npm安装next
4.npm run dev启动项目

**Comment by XiaoSiHwang** [comment]
> 

我是npm run build找不到静态文件，后面我看了下ts部署发现原来与vue部署不同哈哈哈哈我以为是生产静态文件

**Comment by joyol** [comment]
> > 
> 
> 我是npm run build找不到静态文件，后面我看了下ts部署发现原来与vue部署不同哈哈哈哈我以为是生产静态文件

我build没报错，没找到build了个啥

**Comment by emeiziying** [comment]
先build，静态文件在.next里面，然后npm run strat,起node服务
