### ISSUE TITLE
关于增加词语黑名单建议

### ISSUE THREAD

**Issue by VistaQvQ** [guaguaguaxia/weekly_report#8]
测试了一些不和谐的内容，结果没有做屏蔽，直接生成了周报，建议部分词语做黑名单处理。

**Comment by guaguaguaxia** [comment]
做不了，审核机制是一个极其庞大且复杂的黑箱，不是我一个个人开发者可以轻松规避的。如果后续有不可抗力风险，我只能直接下线此服务。
